name: Front End Continuous Deployment

on:
  push:
    branches:
      - main


jobs:
  Deploy-Jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Installing YQ
        run: |
          sudo apt-get update && sudo apt-get install -y yq
          yq --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lksdiycc2025-fe
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{secrets.EKS_CLUSTER_NAME }} --region ${{secrets.AWS_REGION}}

      - name: Deploy to EKS
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: lksdiycc2025-fe
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/lksdiycc2025-fe:${{ github.sha }}
        run: |
          kubectl set image deployment/lksdiycc2025-fe-deployment lksdiycc2025-fe-container=$IMAGE_NAME 
          kubectl rollout restart deployment/lksdiycc2025-fe-deployment
          kubectl get po -l app=lksdiycc2025-fe-pod -o wide
